name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.36
        sudo apt-get update
        sudo apt-get install -y openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev cmake libffi-dev libssl-dev

    - name: Build APK with Buildozer
      working-directory: ./mobile
      run: |
        echo "Building from mobile directory"
        ls -la
        # Buildozer с автоматическим принятием лицензий
        yes | buildozer android debug || buildozer android debug
      env:
        BUILDOZER_LOG_LEVEL: 2
        ANDROID_SDK_ROOT: /home/runner/.buildozer/android/platform/android-sdk
        ANDROID_HOME: /home/runner/.buildozer/android/platform/android-sdk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: epdparser-debug-apk
        path: mobile/bin/*.apk
        retention-days: 30

    - name: Create Release (on tag)
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: mobile/bin/*.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

